# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJDxSuNjRP_kKl6o_hdTol4RrKt5-Eon
"""

import pandas as pd
from tabulate import tabulate

file_name='video_games.csv'

df=pd.read_csv("video_games1.csv")

print(df.head())



# Função para buscar jogos
def buscar_jogos():
    nome_jogo = input('Digite parte do nome do jogo que deseja buscar: ')
    jogos_encontrados = df[df['Title'].str.lower().str.contains(nome_jogo.lower())]
    jogos_encontrados['Title'] = jogos_encontrados['Title'].apply(lambda x: x.title())
    tabela = tabulate(jogos_encontrados[['Title', 'Features.Handheld?', 'Features.Max Players', 'Metadata.Genres', 'Metadata.Publishers']], headers='keys', tablefmt='grid')
    if not jogos_encontrados.empty:
        print(tabela)
    else:
        print('Nenhum jogo encontrado com esse nome.')

buscar_jogos()